apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ram-ncompass/argoCD-usecase.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc # endpoint of k8s api server
    namespace: default